let assetObject = {
    propertyType: "",
    negotable: "",
    price: 0,
    ownership: "",
    propertyAge: "",
    propertyApproved: "",
    propertyDescription: "",
    bankLoan: "",
    length: 0,
    breath: 0,
    totalArea: 0,
    areaUnit: "",
    noOfBHK: 0,
    noOfFloor: 0,
    attached: "",
    western: "",
    furnished: "",
    carParking: "",
    lift: "",
    electricity: "",
    facing: "",
    name: "",
    mobile: 0,
    postedBy: "",
    saleType: "",
    featuredPackage: "",
    ppdPackage: "",
    email: "",
    city: "",
    area: "",
    pincode: 0,
    address: "",
    landmark: "",
    latitude: "",
    longitude: ""
}

module.exports = assetObject;